### ISSUE TITLE
Error when signing in with demo account

### ISSUE THREAD

**Issue by briankariuki** [3Stones-io/omedis#451]
I just created demo accounts with `mix seed.demo` and used one of the accounts to sign in. Here is the output from the logs when signing in and being redirected to `/edit_profile`

```
[error] ** (Ash.Error.Invalid) Invalid Error

* expected at most one result but got at least 2.

    Please ensure your action is configured with an appropriate filter to ensure a single result is returned.
  (elixir 1.17.3) lib/process.ex:864: Process.info/2
  (ash 3.4.36) lib/ash/error/invalid/multiple_results.ex:5: Ash.Error.Invalid.MultipleResults.exception/1
  (ash 3.4.36) lib/ash/helpers.ex:334: Ash.Helpers.unwrap_one/1
  (ash 3.4.36) lib/ash/helpers.ex:316: Ash.Helpers.unwrap_one/1
  (ash 3.4.36) lib/ash.ex:2130: Ash.do_read_one/3
  (ash 3.4.36) lib/ash.ex:2077: Ash.read_one/2
  (ash 3.4.36) lib/ash.ex:2042: Ash.read_one!/2
  (omedis 0.1.0) lib/omedis/accounts/checks/can_delete_account.ex:23: Omedis.Accounts.CanDeleteAccount.not_the_only_admin?/1
  (omedis 0.1.0) lib/omedis/accounts/checks/can_delete_account.ex:6: Omedis.Accounts.CanDeleteAccount.strict_check/3
  (ash 3.4.36) lib/ash/policy/policy.ex:183: Ash.Policy.Policy.fetch_or_strict_check_fact/2
  (ash 3.4.36) lib/ash/policy/policy.ex:431: Ash.Policy.Policy.handle_constants/2
  (ash 3.4.36) lib/ash/policy/policy.ex:390: Ash.Policy.Policy.handle_constants/2
  (ash 3.4.36) lib/ash/policy/policy.ex:409: Ash.Policy.Policy.handle_constants/2
  (ash 3.4.36) lib/ash/policy/policy.ex:385: Ash.Policy.Policy.handle_constants/2
  (ash 3.4.36) lib/ash/policy/policy.ex:390: Ash.Policy.Policy.handle_constants/2
  (ash 3.4.36) lib/ash/policy/policy.ex:29: Ash.Policy.Policy.solve/1
  (ash 3.4.36) lib/ash/policy/checker.ex:65: Ash.Policy.Checker.strict_check_scenarios/1
  (ash 3.4.36) lib/ash/policy/authorizer/authorizer.ex:1618: Ash.Policy.Authorizer.strict_check_result/2
  (ash 3.4.36) lib/ash/policy/authorizer/authorizer.ex:641: Ash.Policy.Authorizer.strict_check/2
  (ash 3.4.36) lib/ash/can.ex:464: anonymous fn/6 in Ash.Can.run_check/4
    (elixir 1.17.3) lib/process.ex:864: Process.info/2
    (ash 3.4.36) lib/ash/error/invalid.ex:3: Ash.Error.Invalid.exception/1
    (ash 3.4.36) /Users/brian/Documents/Work/omedis/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.4.36) lib/ash/error/error.ex:66: Ash.Error.to_error_class/2
    (ash 3.4.36) lib/ash.ex:2081: anonymous fn/1 in Ash.read_one/2
    (ash 3.4.36) lib/ash.ex:2042: Ash.read_one!/2
    (omedis 0.1.0) lib/omedis/accounts/checks/can_delete_account.ex:23: Omedis.Accounts.CanDeleteAccount.not_the_only_admin?/1
    (omedis 0.1.0) lib/omedis/accounts/checks/can_delete_account.ex:6: Omedis.Accounts.CanDeleteAccount.strict_check/3
    (ash 3.4.36) lib/ash/policy/policy.ex:183: Ash.Policy.Policy.fetch_or_strict_check_fact/2
    (ash 3.4.36) lib/ash/policy/policy.ex:431: Ash.Policy.Policy.handle_constants/2
    (ash 3.4.36) lib/ash/policy/policy.ex:390: Ash.Policy.Policy.handle_constants/2
    (ash 3.4.36) lib/ash/policy/policy.ex:409: Ash.Policy.Policy.handle_constants/2
    (ash 3.4.36) lib/ash/policy/policy.ex:385: Ash.Policy.Policy.handle_constants/2
    (ash 3.4.36) lib/ash/policy/policy.ex:390: Ash.Policy.Policy.handle_constants/2
    (ash 3.4.36) lib/ash/policy/policy.ex:29: Ash.Policy.Policy.solve/1
    (ash 3.4.36) lib/ash/policy/checker.ex:65: Ash.Policy.Checker.strict_check_scenarios/1
    (ash 3.4.36) lib/ash/policy/authorizer/authorizer.ex:1618: Ash.Policy.Authorizer.strict_check_result/2
    (ash 3.4.36) lib/ash/policy/authorizer/authorizer.ex:641: Ash.Policy.Authorizer.strict_check/2
    (ash 3.4.36) lib/ash/can.ex:464: anonymous fn/6 in Ash.Can.run_check/4
    (elixir 1.17.3) lib/enum.ex:4858: Enumerable.List.reduce/3
```

**Comment by almirsarajcic** [comment]
Thanks, @briankariuki!

**Comment by briankariuki** [comment]
I've recreated my local database with `mix ecto.reset` then run the seeds command again. I did not experience this issue.
Might be caused by running the seed command twice.

**Comment by almirsarajcic** [comment]
This is stale.
@kagure-nyakio worked on this as part of various issues and fixed all seeds.
We now have a check for running seeds multiple times: `mix check_seeds` - we run that twice as part of the `make check_code` command.
